USE master
GO

CREATE DATABASE QuanLySVTC
GO

USE   QuanLySVTC
GO
CREATE TABLE MonHoc
(
	ID VARCHAR(10) PRIMARY KEY,
	Ten NVARCHAR(50) NOT NULL UNIQUE,
	SoTietLyThuyet INT  DEFAULT 0 CHECK(SoTietLyThuyet >=0),
	SoTietThucHanh INT  DEFAULT 0 CHECK (SoTietThucHanh >=0),
	SoTinChi INT   DEFAULT 2  CHECK (SoTinChi BETWEEN 1 AND 10),
	ThiTotNghiep BIT DEFAULT 0 ,
)
GO
CREATE TABLE GiangVien
(
	ID VARCHAR(10) PRIMARY KEY,
	Ho NVARCHAR(50) NOT NULL,
	Ten NVARCHAR(50) NOT NULL,
	KhoaID VARCHAR(10) NOT NULL,
	HocVi NVARCHAR(50) NOT NULL DEFAULT N'Thạc sĩ',
	HocHam NVARCHAR(50) NOT NULL DEFAULT N'Phó giáo sư',
	ChuyenMon NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE TruongKhoa
(
	ID VARCHAR(10) ,
	Ngay DATE DEFAULT GETDATE(),
	CONSTRAINT PK_TruongKhoa PRIMARY KEY  (ID,Ngay),
	CONSTRAINT FK_TruongKhoa_GiaoVien FOREIGN KEY (ID) REFERENCES dbo.GiangVien(ID)
)
GO
CREATE TABLE Khoa
(
	ID VARCHAR(10) PRIMARY KEY,
	Ten NVARCHAR(50) NOT NULL UNIQUE,
)
GO
ALTER TABLE dbo.GiangVien ADD CONSTRAINT GiangVien_Khoa FOREIGN KEY(KhoaID) REFERENCES Khoa(ID)
GO
CREATE TABLE ChuyenNganh
(
	ID VARCHAR(10) PRIMARY KEY,
	Ten NVARCHAR(50) NOT NULL UNIQUE,
	KhoaID VARCHAR(10) NOT NULL,
	CONSTRAINT FK_ChuyenNganh_Khoa FOREIGN KEY (KhoaID) REFERENCES dbo.Khoa(ID)
)
GO
CREATE TABLE Lop
(
	ID VARCHAR(10) PRIMARY KEY,
	Ten NVARCHAR(50) NOT NULL UNIQUE,
	KhoaID VARCHAR(10) NOT NULL,
	CONSTRAINT FK_Lop_Khoa FOREIGN KEY (KhoaID) REFERENCES dbo.Khoa(ID)
)
GO

CREATE TABLE KeHoachGiang
(
	MonHocID VARCHAR(10) NOT NULL,
	ChuyenNganhID VARCHAR(10) NOT NULL,	
	Ngay DATE  DEFAULT GETDATE() CHECK (Ngay >= GETDATE()),
	HocKy INT  DEFAULT 1 CHECK (HocKy BETWEEN 1 AND 2),
	NienKhoa INT  DEFAULT YEAR(GETDATE()),

	CONSTRAINT PK_KeHoachGiang PRIMARY KEY(MonHocID,ChuyenNganhID,Ngay),
	CONSTRAINT FK_MonHoc FOREIGN KEY(MonHocID) REFERENCES dbo.MonHoc(ID),
	CONSTRAINT FK_ChuyenNganh FOREIGN KEY(ChuyenNganhID) REFERENCES dbo.ChuyenNganh(ID),
)
GO
CREATE TABLE KhaNangDayHoc
(
	MonHocID VARCHAR(10) NOT NULL,
	GiangVienID VARCHAR(10) NOT NULL,
	CONSTRAINT PK_KhaNangDayHoc PRIMARY KEY(MonHocID,GiangVienID),
	CONSTRAINT FK_KhaNang_MonHoc FOREIGN KEY (MonHocID) REFERENCES dbo.MonHoc(ID),
	CONSTRAINT FK_KhaNang_GiangVien FOREIGN KEY (GiangVienID) REFERENCES dbo.GiangVien(ID)
)

GO
CREATE TABLE SinhVien
(
	ID VARCHAR(10) PRIMARY KEY,
	Ho NVARCHAR(50) NOT NULL,
	Ten NVARCHAR(50) NOT NULL,
	Phai NVARCHAR(3)  DEFAULT N'Nữ' CHECK(Phai = N'Nam' OR Phai =N'Nữ'),
	DiaChi NTEXT,
	NgaySinh DATE NOT NULL,
	KhoaHoc INT   DEFAULT YEAR(GETDATE()),
	XetLVTN INT DEFAULT NULL CHECK (XetLVTN IS NULL OR XetLVTN = 0 OR XetLVTN =1),
	ChuyenNganhID VARCHAR(10),
	LopID VARCHAR(10) NOT NULL,
	CONSTRAINT FK_SinhVien_Lop FOREIGN KEY(LopID) REFERENCES dbo.Lop(ID),
	CONSTRAINT FK_SinhVien_ChuyenNganh FOREIGN KEY(ChuyenNganhID) REFERENCES dbo.ChuyenNganh(ID)
)
GO
	CREATE TABLE LopTinChi
	(
		ID INT IDENTITY PRIMARY KEY,
		GiangVienID VARCHAR(10) NOT NULL,
		MonHocID VARCHAR(10) NOT NULL,
		Nhom INT NOT NULL CHECK(Nhom >=1 AND Nhom <= 20),
		NienKhoa INT   DEFAULT YEAR(GETDATE()),
		HocKy INT  DEFAULT 1 CHECK(HocKy BETWEEN 1 AND 3),
		SoSVToiTieu INT  DEFAULT 10 CHECK (SoSVToiTieu >0),
		SoSVToiDa INT  DEFAULT 70,

		NgayBatDau DATE  DEFAULT GETDATE() CHECK (NgayBatDau > GETDATE()),
		NgayKetThuc DATE NOT NULL,


		CONSTRAINT CK_LopTinChi_SoSVToiDa CHECK (SoSVToiDa >= SoSVToiTieu),
		CONSTRAINT CK_LopTinChi_NgayKetThuc CHECK (NgayKetThuc > NgayBatDau),
		CONSTRAINT FK_LopTinChi_KhaNang FOREIGN KEY(MonHocID,GiangVienID) REFERENCES dbo.KhaNangDayHoc(MonHocID,GiangVienID)
	)
CREATE TABLE ChiTietLichHoc
(
	LopTinChiID INT NOT NULL,
	Buoi CHAR(1)  CHECK(Buoi = 'S' OR Buoi = 'C') DEFAULT 'S',
	Thu INT CHECK (Thu >=2 AND Thu <= 7) NOT NULL,
	Phong VARCHAR(10) NOT NULL,
	TietBatDau INT  DEFAULT 1 CHECK(TietBatDau>=1 AND TietBatDau <=10),
	SoTiet INT  DEFAULT 4 CHECK (SoTiet <= 5),

	CONSTRAINT PK_LichHoc PRIMARY KEY(LopTinChiID,Buoi,Thu),
	CONSTRAINT FK_LichHoc_LopTinChi FOREIGN KEY(LopTinChiID) REFERENCES dbo.LopTinChi(ID)
)



create TABLE DangKy
(
	SinhVienID VARCHAR(10) NOT NULL,
	LopTinChiID INT NOT NULL,

	CONSTRAINT PK_DangKyLopTinChi PRIMARY KEY (SinhVienID,LopTinChiID),
	CONSTRAINT FK_DangKy_SinhVien FOREIGN KEY (SinhVienID) REFERENCES dbo.SinhVien(ID),
	CONSTRAINT FK_DangKy_LopTinChi FOREIGN KEY (LopTinChiID) REFERENCES dbo.LopTinChi(ID),
)
GO
CREATE TABLE LuanVanTN
(
	ID VARCHAR(10) PRIMARY KEY,
	DiemHuongDan INT CHECK (DiemHuongDan IS NULL OR DiemHuongDan BETWEEN 0 AND 10),
	DiemPhanBien INT CHECK (DiemPhanBien IS NULL OR DiemPhanBien BETWEEN 0 AND 10),
	SinhVienID VARCHAR(10) NOT NULL,
	GVHD_ID VARCHAR(10) NOT NULL,
	GVPB_ID VARCHAR(10) NOT NULL,
	CONSTRAINT FK_LuanVanTN_SinhVien FOREIGN KEY(SinhVienID) REFERENCES dbo.SinhVien(ID),
	CONSTRAINT FK_LuanVanTN_GVHD FOREIGN KEY(GVHD_ID) REFERENCES dbo.GiangVien(ID),
	CONSTRAINT FK_LuanVanTN_GVPB FOREIGN KEY(GVPB_ID) REFERENCES dbo.GiangVien(ID),
)

GO
CREATE TABLE HoiDongBaoCao
(
	ID VARCHAR(10) PRIMARY KEY,
	Ten NVARCHAR(50) NOT NULL UNIQUE,
	Nam INT DEFAULT YEAR(GETDATE()) UNIQUE,
	KhoaID VARCHAR(10) NOT NULL,
	CONSTRAINT FK_HoiDong_Khoa FOREIGN KEY(KhoaID) REFERENCES dbo.Khoa(ID)
)

GO
CREATE TABLE TieuBan
(
	ID VARCHAR(10) PRIMARY KEY,
	Ten NVARCHAR(50) NOT NULL UNIQUE,
	HoiDongID VARCHAR(10) NOT NULL,
	ChuyenNganhID VARCHAR(10) NOT NULL,
	CONSTRAINT FK_TieuBan_HoiDong FOREIGN KEY(HoiDongID) REFERENCES dbo.HoiDongBaoCao(ID),
	CONSTRAINT FK_TieuBan_CN FOREIGN KEY(ChuyenNganhID) REFERENCES dbo.ChuyenNganh(ID)
)

CREATE TABLE CTTieuBan
(
	ID INT IDENTITY PRIMARY KEY,
	GiangVienID VARCHAR(10) NOT NULL,
	TieuBanID VARCHAR(10) NOT NULL,

	CONSTRAINT FK_CTTieuBan_GiangVien FOREIGN KEY(GiangVienID) REFERENCES dbo.GiangVien(ID),
	CONSTRAINT FK_CTTieuBan_HoiDong FOREIGN KEY(TieuBanID) REFERENCES dbo.TieuBan(ID)
)

GO
CREATE TABLE ChamLVTN
(
	CTTieuBanID INT,
	LuanVanID VARCHAR(10) NOT NULL,
	Diem INT NOT NULL CHECK (Diem BETWEEN 0 AND 10),
	CONSTRAINT PK_ChamLVTN PRIMARY KEY(CTTieuBanID,LuanVanID),
	CONSTRAINT FK_ChamLVTN_LVTN FOREIGN KEY (LuanVanID) REFERENCES dbo.LuanVanTN(ID),
	CONSTRAINT FK_ChamLVTN_CTTieuBan FOREIGN KEY(CTTieuBanID) REFERENCES dbo.CTTieuBan(ID)
)

GO



CREATE TABLE LoaiDiem
(
	ID VARCHAR(10) PRIMARY KEY,
	Ten NVARCHAR(50) NOT NULL UNIQUE,
	PhanTram FLOAT NOT NULL
)


CREATE TABLE CTPhanTramDiemLopTC
(
	LoaiDiemID VARCHAR(10),
	LopTC_ID INT,
	CONSTRAINT PK_CTPhanTramDiemLopTC PRIMARY KEY(LoaiDiemID,LopTC_ID),
	CONSTRAINT FK_CTPhanTramDiemLopTC_LopTC FOREIGN KEY(LopTC_ID) REFERENCES dbo.LopTinChi(ID),
	CONSTRAINT FK_CTPhanTramDiemLopTC_LoaiDIem FOREIGN KEY(LoaiDiemID) REFERENCES dbo.LoaiDiem(ID)

)
GO
CREATE TABLE CTDiemSV
(
	LoaiDiemID VARCHAR(10),
	SinhVienID VARCHAR(10) NOT NULL,
	LopTC_ID INT NOT NULL,
	Diem FLOAT NOT NULL,
	CONSTRAINT PK_CTDiemSV PRIMARY KEY(LoaiDiemID,SinhVienID,LopTC_ID),
	CONSTRAINT FK_CTDiemSV FOREIGN KEY(LoaiDiemID,LopTC_ID) REFERENCES dbo.CTPhanTramDiemLopTC(LoaiDiemID,LopTC_ID),

)
ALTER TABLE dbo.CTDiemSV ADD CONSTRAINT FK_CTDiemSV_DangKy FOREIGN KEY(SinhVienID,LopTC_ID) REFERENCES dbo.DangKy(SinhVienID,LopTinChiID)

	
	




